---
- hosts: all
  vars_files:
    - lamp_vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cach=yes cache_valid_time=3600

  tasks:
    - name: " 安装用来管理ATP源的工具 "
      apt: name={{ item }} state=present
      with_items:
        - python-apt
        - python-pycurl

    - name: "添加包含5.5版本PHP的ondrej源"
      apt_repository: repo='ppa:ondrej/php5' update_cache=yes

    - name: "安装Apache、MySQL、PHP，以及依赖关系"
      apt: name={{ item }} state=present
      with_items:
        - git
        - curl
        - sendmail
        - apache2
        - php5
        - php5-common
        - php5-mysql
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-dev
        - php5-mcrypt
        - php-apc
        - php-pear
        - python-mysqldb
        - mysql-server

    - name: "关闭防火墙（仅开发环境）"
      service: name=ufw state=stopped

    - name: "启动Apache、MySQL及PHP"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2
        - mysql

    - name: Enable Apache rewrite module (required for Drupal)
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: 在Apache中为Drupal添加virtualhost
      template:
        src: "templates/drupal.dev.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: 在sites-enabled目录中添加Drupal所需配置文件的符号链接
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.dev.conf"
        state: link
      notify: restart apache

    - name: Enable upload progress via APC.
      lineinfile:
        dest: "/etc/php5/apache2/conf.d/20-apcu.ini"
        regexp: "^apc.rfc1867"
        line: "apc.rfc1867 = 1"
        state: present
      notify: restart apache

    - name: 删除test数据库
      mysql_db: db=test state=absent
    - name: 为Drupal创建新库
      mysql_db: "db={{ domain }} state=present"

    - name: Download Composer installer.
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Run Composer installer.
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Move Composer into globally-accessible location
      shell: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer

    - name: 从Github中下载Drush代码
      git:
        repo: https://github.com/drush-ops/drush.git
        dest: /opt/drush

    - name: 使用composer安装drush
      shell: >
        /usr/local/bin/composer install
        chdir=/opt/drush
        creates=/opt/drush/vendor/autoload.php

    - name: 创建drush命令的符号链接
      file:
        src: /opt/drush/drush
        dest: /usr/local/bin/drush
        state: link

    - name: 下载drupal代码到apache的documentRoot
      git:
        repo: http://git.drupal.org/project/drupal.git
        version: "{{  drupal_core_version }}"
        dest: "{{ drupal_core_path }}"

    - name: 安装Drupal
      command: >
        drush si -y --site-name="{{ drupal_site_name }}" --account-name=admin
        --account-pass=admin --db-url=mysql://root@localhost/{{ domain }}
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/sites/default/settings.php
      notify: restart apache

    - name: 为settings.php设置正确的权限
      file:
        path: "{{ drupal_core_path }}/sites/default/settings.php"
        mode: 0744

    - name: 开放files目录的所有权限
      file:
        path: "{{ drupal_core_path }}/sites/default/files"
        mode: 0777
        state: directory
        recurse: yes

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
