---
- hosts: all
  tasks:
    - name: add virtual-box repo
      command: echo "[virtualbox]
        name=Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
        baseurl=http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://www.virtualbox.org/download/oracle_vbox.asc" > /etc/yum.repos.d/virtualbox.repo

    - name: update yum repo
      command: yum clean all && yum makecache

    - name: setup virtualbox
      command: yum install VirtualBox-6.0 -y